// 07 - Component/1. Registration/b. Local/i. Basics/composition-api/compiled/js/src/App.vue
<!-- European Union Public License version 1.2 -->
<!-- Copyright © 2018 Rick Beerendonk          -->

<script setup>
import { ref } from 'vue';
import GreetingComponent from './components/GreetingComponent.vue';

const appName = ref('App');
</script>

<template>
  <h1>{{ appName }}</h1>
  <GreetingComponent />
</template>

<style scoped>
h1 {
  color: blue;
}
</style>

// 23 - Render and JSX/b. Attributes/composition-api/jsx/src/App.jsx
// European Union Public License version 1.2
// Copyright © 2024 Rick Beerendonk

// IMPORTANT: Filename must end with ".jsx" to enable JSX transpilation.

export default {
  setup() {
    return function render() {
      return (
        <a href="https://vuejs.org" target="_blank">
          Vue website
        </a>
      );
    };
  }
};
