// 23 - Render and JSX/b. Attributes/composition-api/jsx/src/App.jsx
// European Union Public License version 1.2
// Copyright © 2024 Rick Beerendonk

// IMPORTANT: Filename must end with ".jsx" to enable JSX transpilation.

export default {
  setup() {
    return function render() {
      return (
        <a href="https://vuejs.org" target="_blank">
          Vue website
        </a>
      );
    };
  }
};

// Debugging/a. Basics/composition-api/src/App.vue
<!-- European Union Public License version 1.2 -->
<!-- Copyright © 2019 Rick Beerendonk          -->

<template>
  <div id="app">
    <GreetingEditor value="Vue" />
  </div>
</template>

<script setup>
import GreetingEditor from './components/GreetingEditor.vue';
</script>

<style>
#app {
  color: #444;
}
</style>
